### ISSUE TITLE
How to get data from page type?

### ISSUE THREAD

**Issue by ledinhminh98** [HBSTech/Kentico13CoreBaseline#13]
I have created the page type ( screenshot ), can you show me how to get TEXT content in code? ( Privacy Policy is a page )
![image](https://user-images.githubusercontent.com/71751434/165014235-bc468364-5a48-4390-ac8d-5fdc8c009fc9.png)

**Comment by KenticoDevTrev** [comment]
Not sure this is the right channel to ask this question as it's unrelated to the baseline.

I would go through the developer tutorial: https://docs.xperience.io/13tutorial/developer-tutorial as getting data from Xperience is one of the most basic elements of building with the tool, so you'll want to get yourself familiar with Xperience itself and it's APIs.  the baseline has examples of getting data from a page type and has info in the wiki on it's methedology for doing so, which i encourage you to follow.

If you want as well, there is on devnet.kentico.com a Q&A secction, and if you provide your email address i can add you to the kentico community slack channel.

**Comment by ledinhminh98** [comment]
@KenticoDevTrev
Can you add me to the kentico community slack channel?
This is my email: ldminh8398@gmail.com
Thank you!

**Comment by KenticoDevTrev** [comment]
Done!
