### ISSUE TITLE
Misleading optional parameter in view component

### ISSUE THREAD

**Issue by ChristopherBass** [HBSTech/Kentico13CoreBaseline#4]
In \Components\Navigation\MainNavigationViewComponent.cs,  the signature of InvokeAsync is:
        public async Task<IViewComponentResult> InvokeAsync(string NavigationParentPath, string CssClass = "MainNav")
        
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-5.0

See the bottom:

> **All view component parameters are required**
> Each parameter in a view component is a required attribute. See this GitHub issue. If any parameter is omitted:
> 
> - The InvokeAsync method signature won't match, therefore the method won't execute.
> - The ViewComponent won't render any markup.
> - No errors will be thrown.

  Back when the optional parameter was "CurrentPage", I'd attempted to have it default using the ViewBag logic that was in there at the time - but instead it just rendered nothing, with no error. Have you tried it out with the CSS Class being not passed in? I suspect you'll see the same situation, where it just won't match up unless all (even optional) parameters are passed in the tag helper.

**Comment by KenticoDevTrev** [comment]
Hey Chris, sorry i never got notice of this.

Sadly all view component properties are required, even if it has a value set, it's a .net core thing right now, i think .net core 6 they added this feature in, and i know that Kentico is testing KX13 for .net 6 and hopefully in the next couple releases it will be there.
