### ISSUE TITLE
Misleading signature to method BasicUserToIUser

### ISSUE THREAD

**Issue by ChristopherBass** [HBSTech/Kentico13CoreBaseline#5]
The method 'BasicUserToIUser' in line 15 of the IUserService says in both its name and its comment that it returns an IUserInfo object (CMS.Base.IUserInfo), but instead it returns a CMS.Membership.UserInfo.  

(UserInfo implements IUserInfo)

**Comment by KenticoDevTrev** [comment]
Sorry about that.  This was actually refactored in the new revision to not even return a Kentico type, but instead a agnostic User object.
