### ISSUE TITLE
Broken link to site import in readme

### ISSUE THREAD

**Issue by hades200082** [HBSTech/Kentico13CoreBaseline#6]
Instructions in the readme say to download the "Baseline Site" (URL: https://github.com/HBSTech/Kentico13CoreBaseline/blob/master/Kentico13CoreBaseline-AdminSiteImport.zip ) and import it into the newly installed K13 site - but the URL 404's

This makes the baseline unusable to new developers since the instructions can't be followed.

**Comment by KenticoDevTrev** [comment]
Fixed, sorry I think I changed the file name mid way and forgot to update the doc. 

Also repull the repository, a fix wasn't there for some reason on the cache names. Good luck!
