### ISSUE TITLE
Breadcrumb create empty link extra

### ISSUE THREAD

**Issue by rafik4000** [HBSTech/Kentico13CoreBaseline#9]
Hello, I found out the Breadcrumb create an extra empty Breadcrumb
![Screenshot 2022-01-27 231459](https://user-images.githubusercontent.com/33886387/151486521-87d3029e-594e-4457-9f41-619e41be5ff7.png)

**Comment by KenticoDevTrev** [comment]
I'll look into this one!

**Comment by KenticoDevTrev** [comment]
@rafik4000  Sorry took so long to get to.  Found bug in the breadcrumb repo, fixed! [commit](https://github.com/HBSTech/Kentico13CoreBaseline/commit/a3f5f4e523a97f0c036deae046a64ee3169a50b8)
